---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 5a67173e7621204122a26c2b0ebe632eb01000d0
ms.sourcegitcommit: 21d667104199c2493accec20c2388cf674b195c3
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 02/08/2019
ms.locfileid: "55919363"
---
# <a name="c6312"></a>C6312
avertissement C6312 : Boucle infinie possible : utilisation de la constante EXCEPTION_CONTINUE_EXECUTION dans l’expression de filtre d’exception d’un bloc try-à l’exception

 Cet avertissement indique l’utilisation de la constante `EXCEPTION_CONTINUE_EXECUTION` (ou une autre constante égale à -1) dans l’expression de filtre d’un gestionnaire d’exceptions structurées. Utilisation de la valeur de constante `EXCEPTION_CONTINUE_EXECUTION` peut entraîner une boucle infinie. Par exemple, si une exception a été levée par le matériel, l’instruction qui a provoqué l’exception est redémarrée. Si l’adresse qui a provoqué l’exception est toujours incorrect, une autre exception se produira et être traitée de la même façon. Cela provoque une boucle infinie.

 Un appel explicite à `RaiseException` ne provoquera pas directement une boucle infinie, mais poursuit l’exécution du code dans le bloc protégé. Cela peut être inattendu et peut entraîner une boucle infinie si `RaiseException` a été utilisé pour éviter de déréférencer un pointeur non valide.

 En règle générale, `EXCEPTION_CONTINUE_EXECUTION` doit être retournée que si une fonction appelée dans l’expression de filtre qui a une chance de corriger soit le pointeur qui a provoqué l’exception, soit la mémoire sous-jacente.

## <a name="example"></a>Exemple
 Le code suivant génère cet avertissement :

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Pour corriger cet avertissement, utilisez le code suivant :

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```